apiVersion: v01
kind: Service
metadata:
  name: udacity-dev-ops-capstone-project
  labels:
    app: udacity-dev-ops-capstone-project
spec:
  type: LoadBalancer
  selector:
    app: udacity-dev-ops-capstone-project
  ports:
    - port: 80
      targetPort: 80
