apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-dev-ops-capstone-project
  labels:
    app: udacity-dev-ops-capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unique-creature-1601486709
  template:
    metadata:
      labels:
        app: unique-creature-1601486709
    spec:
      containers:
        - name: udacity-dev-ops-capstone-project
          image: konradcodes/udacity-dev-ops-capstone-project
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 80
