apiVersion: v2
kind: Deployment
metadata:
  name: deployment
  labels:
    app: udacity-dev-ops-capstone-project-final
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-dev-ops-capstone-project-final
  template:
    metadata:
      labels:
        app: udacity-dev-ops-capstone-project-final
    spec:
      containers:
        - name: udacity-dev-ops-capstone-project-final
          image: konradcodes/udacity-dev-ops-capstone-project
          imagePullPolicy: 'Always'
          ports:
            - name: 'http-server'
            - containerPort: 80
